import type { Metadata } from 'next'
import { Noto_Kufi_Arabic } from 'next/font/google'
import '../globals.css'
import Header from '@/components/navigation/header'
import { Locale } from '@/lib/i18n'

 type Params = { lang:  Locale}

 
 
const kufi = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  display: 'swap',
  weight: ['400', '500', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params:Promise<Params>
   
}>) {
  const {lang} = await params
   
  
  return (
    <html lang={lang} dir={`${lang === "ar" ? "rtl" : "ltr"}`}>
      <body className={`${kufi.className} antialiased`}>
       
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1">{children}</main>
            {/* <Footer /> */}
          </div>
         
      </body>
    </html>
  )
}

 